<%@ Page Language ="C#" Inherits="Controls" CodeFile="Controls.aspx.cs" %>
<html>
    <head><title>Control-Elements</title></head>
    <body>
        <!-- Button mit Fonts -->
        <asp:Button ID="button" Font-Name="Arial" Font-Size="Large" Font-Bold="true" OnClick="DoClick"/>

        <!-- Command umd Argumente zu übergeben und mehrere Button mit gleicher Eventhanler  -->
        <asp:Button ID="b1" CommandName="command1" CommandArgument="1" OnCommand="DoCommand"/>
        <asp:Button ID="b2" CommandName="command2" CommandArgument="2" OnCommand="DoCommand"/>
        <!-- Code -->
        public void DoCommand(Object sender, CommandEventArgs e) {
            if (e.CommandName == "command1"){
                // Command 1 pressed
            } else {
                // Command 2 pressed
            }
            Console.Write( Convert.ToInt(e.CommandArgument)) // Auf das Argument zugreifen
        }

        <!-- Textbox -->
        <asp:TextBox Text="Platzhalter" OnTextChanged="DoChange" Runat="server"/>
        <asp:TextBox Type="Password" MaxLength="10" Runat="server"/>
        <asp:TextBox TextMode="MultiLine" Rows="5" Columns="20" Wrap="true" Runat="server"/>

        <!-- Checkbox -->
        <asp:CheckBox ID="chechk1" text="Option1" runat="server" />
        <asp:CheckBox ID="chechk2" text="Option2" runat="server" />
        <asp:Button Text="Confirm" OnClick="DoCheck" runat="server"/>
        <!-- Code -->
        public void DoCheck(Object sender, CommandEventArgs e) {
            if (check1.Checked) {
                // Option 1 checked
            }...
        }

        <!-- RadioButton -->
        <asp:RadioButton ID="radio1" Text="Option1" GroupName="group1" OnCheckedChange="RadioChange" runat="server"/>
        <asp:RadioButton ID="radio2" Text="Option2" GroupName="group1" OnCheckedChange="RadioChange" runat="server"/>
        <!-- Code -->
        public void RadioChange(Object sender, CommandEventArgs e) {
            if (radio1.Checked) {
                // Option 1 checked
            }...
        }

        <!-- ListBox: ListControl -->
        <asp:ListBox ID="list" Rows="3" OnSelectedIndexChanged="HandleSelect" runat="server">
            <asp:ListItem Text="Option1" Value="1"/>
            <asp:ListItem Text="Option2" Value="2"/>
            <asp:ListItem Text="Option3" Value="3"/>
        </asp:ListBox>
        <!-- Code für dynamische Liste (oben ist statisch) -->
        public void CreateList(Object sender, CommandEventArgs e) {
            SortedList data = new SortedList();
            data["Option1"] = 1;
            data["Option2"] = 2;
            data["Option3"] = 3;
            list.DataSource = data;
            list.DataTextField = "Key"; // Nimmt Text aus dem Key
            list.DataValueField = "Value"; // Nimmt den Value aus Value
            list.DataBind();
            
            // Oder Daten direkt aus DB laden:
            list.DataSource = ds.Tables["Person"].DefaultView;
            list.DataBind();
        }

        <!-- DropDownList: ListControl / AutoPostBack -> Schickt die gemerkte Auswahl direkt an Server -->
        <asp:DropDownList ID="dropList" OnSelectedIndexChanged="HandleDropdownChange" AutoPostBack="true" runat="server">
            <asp:ListItem Text="Option1" Value="1"/>
            <asp:ListItem Text="Option2" Value="2"/>
            <asp:ListItem Text="Option3" Value="3"/>
         </asp:DropDownList>
     

        <!-- Grid View: Visualisierung einer DB -->
        <asp:GridView ID="grid" DataSourceID="data" Runat="server" AllowSorting="true" />
        <asp:GridView ID="grid" DataSource="data" Runat="server"  
            DataKeyNames="id" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true"/>

        <!-- AccessDataSource, SqlDataSource, XmlDataSource, ObjectDataSource, SiteMapDataSource -->
        <!-- @id = Spaltenname -->
        <asp:AccessDataSource ID="data" DataFile=db.mdb" 
            SelectCommand="SELECT id, name FROM Table" 
            UpdateCommand="UPDATE Table SET name=@name WHERE id=@id"
            DeleteCommand="DELETE FROM Table id=@id"
            runat="server"/>

        <!-- DropDown mit Daten aus DB (Access, SQL, XML, ....) -->
        <asp:AccessDataSource ID="data" DataFile=db.mdb" 
            SelectCommand="SELECT DISTINCT name FROM Table" runat="server"/>
        <asp:DropDownList DataSourceID="data" DataTextField="name" Runat="server" />


       
    </body>
</html>

